/**
 * Minimal stubs for BasiliskII functions required by UAE CPU
 * These are temporary - will be replaced with real implementations
 * as we pull in more of BasiliskII
 */

#include "sysdeps.h"
#include "cpu_emulation.h"

// Tick counting for timing
uae_u32 emulated_ticks = 0;
void cpu_do_check_ticks(void) {
    // Stub - no timing checks for now
}

// FPU emulation stubs
void fpu_init(bool hard_reset) {
    // Stub - FPU not needed for initial testing
    (void)hard_reset;
}

void fpu_exit(void) {
    // Stub
}

void fpu_reset(void) {
    // Stub
}

void fpu_dump_registers(void) {
    // Stub
}

void fpu_dump_flags(void) {
    // Stub
}

// Idle/resume for interrupt handling
void idle_resume(void) {
    // Stub
}

// EmulOp handler - now using real implementation from src/core/emul_op.cpp
// (removed stub - the real EmulOp is linked from libcore.a)


// Instruction table definitions
// NOTE: Both _ff and _nf tables are now properly generated by gencpu and compiled:
// - _ff tables come from cpustbl.cpp (compiled without NOFLAGS)
// - _nf tables come from cpustbl_nf.cpp (compiled with NOFLAGS)
// No stubs needed here - the real tables are in libcpustbl_ff.a and libuae_cpu.a

// Stubs for instructions that are excluded by NOFLAGS
// (these are typically cache control and supervisor instructions)
void REGPARAM2 op_f43f_0_nf(uae_u32 opcode) { 
    printf("Unimplemented instruction: CPUSHA opcode=0x%04x\n", opcode);
}
void REGPARAM2 op_f500_0_nf(uae_u32 opcode) {
    printf("Unimplemented instruction: PFLUSHA opcode=0x%04x\n", opcode);
}
void REGPARAM2 op_f600_0_nf(uae_u32 opcode) {
    printf("Unimplemented instruction: MOVE16 opcode=0x%04x\n", opcode);
}
void REGPARAM2 op_f608_0_nf(uae_u32 opcode) {
    printf("Unimplemented instruction: MOVE16 opcode=0x%04x\n", opcode);
}
void REGPARAM2 op_f610_0_nf(uae_u32 opcode) {
    printf("Unimplemented instruction: MOVE16 opcode=0x%04x\n", opcode);
}
void REGPARAM2 op_f618_0_nf(uae_u32 opcode) {
    printf("Unimplemented instruction: MOVE16 opcode=0x%04x\n", opcode);
}
void REGPARAM2 op_f43e_0_nf(uae_u32 opcode) {
    printf("Unimplemented instruction: CPUSHA opcode=0x%04x\n", opcode);
}
void REGPARAM2 op_f620_0_nf(uae_u32 opcode) {
    printf("Unimplemented instruction: MOVE16 opcode=0x%04x\n", opcode);
}
void REGPARAM2 x_nf(uae_u32 opcode) {
    printf("Unimplemented instruction: x opcode=0x%04x\n", opcode);
}
void REGPARAM2 op_f43b_0_nf(uae_u32 opcode) {
    printf("Unimplemented instruction: CPUSHA opcode=0x%04x\n", opcode);
}
void REGPARAM2 op_f43c_0_nf(uae_u32 opcode) {
    printf("Unimplemented instruction: CPUSHA opcode=0x%04x\n", opcode);
}
void REGPARAM2 op_f43d_0_nf(uae_u32 opcode) {
    printf("Unimplemented instruction: CPUSHA opcode=0x%04x\n", opcode);
}
void REGPARAM2 op_f200_0_nf(uae_u32 opcode) { printf("Unimplemented: op_f200_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_f208_0_nf(uae_u32 opcode) { printf("Unimplemented: op_f208_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_f210_0_nf(uae_u32 opcode) { printf("Unimplemented: op_f210_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_f218_0_nf(uae_u32 opcode) { printf("Unimplemented: op_f218_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_f220_0_nf(uae_u32 opcode) { printf("Unimplemented: op_f220_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_f228_0_nf(uae_u32 opcode) { printf("Unimplemented: op_f228_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_f230_0_nf(uae_u32 opcode) { printf("Unimplemented: op_f230_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_f238_0_nf(uae_u32 opcode) { printf("Unimplemented: op_f238_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_f239_0_nf(uae_u32 opcode) { printf("Unimplemented: op_f239_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_f23a_0_nf(uae_u32 opcode) { printf("Unimplemented: op_f23a_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_f23b_0_nf(uae_u32 opcode) { printf("Unimplemented: op_f23b_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_f23c_0_nf(uae_u32 opcode) { printf("Unimplemented: op_f23c_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_f240_0_nf(uae_u32 opcode) { printf("Unimplemented: op_f240_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_f248_0_nf(uae_u32 opcode) { printf("Unimplemented: op_f248_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_f250_0_nf(uae_u32 opcode) { printf("Unimplemented: op_f250_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_f258_0_nf(uae_u32 opcode) { printf("Unimplemented: op_f258_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_f260_0_nf(uae_u32 opcode) { printf("Unimplemented: op_f260_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_f268_0_nf(uae_u32 opcode) { printf("Unimplemented: op_f268_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_f270_0_nf(uae_u32 opcode) { printf("Unimplemented: op_f270_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_f278_0_nf(uae_u32 opcode) { printf("Unimplemented: op_f278_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_f279_0_nf(uae_u32 opcode) { printf("Unimplemented: op_f279_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_f27a_0_nf(uae_u32 opcode) { printf("Unimplemented: op_f27a_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_f27b_0_nf(uae_u32 opcode) { printf("Unimplemented: op_f27b_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_f27c_0_nf(uae_u32 opcode) { printf("Unimplemented: op_f27c_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_f280_0_nf(uae_u32 opcode) { printf("Unimplemented: op_f280_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_f2c0_0_nf(uae_u32 opcode) { printf("Unimplemented: op_f2c0_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_f310_0_nf(uae_u32 opcode) { printf("Unimplemented: op_f310_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_f320_0_nf(uae_u32 opcode) { printf("Unimplemented: op_f320_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_f328_0_nf(uae_u32 opcode) { printf("Unimplemented: op_f328_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_f330_0_nf(uae_u32 opcode) { printf("Unimplemented: op_f330_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_f338_0_nf(uae_u32 opcode) { printf("Unimplemented: op_f338_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_f339_0_nf(uae_u32 opcode) { printf("Unimplemented: op_f339_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_f350_0_nf(uae_u32 opcode) { printf("Unimplemented: op_f350_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_f358_0_nf(uae_u32 opcode) { printf("Unimplemented: op_f358_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_f368_0_nf(uae_u32 opcode) { printf("Unimplemented: op_f368_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_f370_0_nf(uae_u32 opcode) { printf("Unimplemented: op_f370_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_f378_0_nf(uae_u32 opcode) { printf("Unimplemented: op_f378_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_f379_0_nf(uae_u32 opcode) { printf("Unimplemented: op_f379_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_f37a_0_nf(uae_u32 opcode) { printf("Unimplemented: op_f37a_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_f37b_0_nf(uae_u32 opcode) { printf("Unimplemented: op_f37b_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_f408_0_nf(uae_u32 opcode) { printf("Unimplemented: op_f408_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_f410_0_nf(uae_u32 opcode) { printf("Unimplemented: op_f410_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_f418_0_nf(uae_u32 opcode) { printf("Unimplemented: op_f418_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_f419_0_nf(uae_u32 opcode) { printf("Unimplemented: op_f419_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_f41a_0_nf(uae_u32 opcode) { printf("Unimplemented: op_f41a_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_f41b_0_nf(uae_u32 opcode) { printf("Unimplemented: op_f41b_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_f41c_0_nf(uae_u32 opcode) { printf("Unimplemented: op_f41c_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_f41d_0_nf(uae_u32 opcode) { printf("Unimplemented: op_f41d_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_f41e_0_nf(uae_u32 opcode) { printf("Unimplemented: op_f41e_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_f41f_0_nf(uae_u32 opcode) { printf("Unimplemented: op_f41f_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_f428_0_nf(uae_u32 opcode) { printf("Unimplemented: op_f428_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_f430_0_nf(uae_u32 opcode) { printf("Unimplemented: op_f430_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_f438_0_nf(uae_u32 opcode) { printf("Unimplemented: op_f438_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_f439_0_nf(uae_u32 opcode) { printf("Unimplemented: op_f439_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_f43a_0_nf(uae_u32 opcode) { printf("Unimplemented: op_f43a_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_108_0_nf(uae_u32 opcode) { printf("Unimplemented: op_108_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_148_0_nf(uae_u32 opcode) { printf("Unimplemented: op_148_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_188_0_nf(uae_u32 opcode) { printf("Unimplemented: op_188_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_1c8_0_nf(uae_u32 opcode) { printf("Unimplemented: op_1c8_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_2040_0_nf(uae_u32 opcode) { printf("Unimplemented: op_2040_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_2048_0_nf(uae_u32 opcode) { printf("Unimplemented: op_2048_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_2050_0_nf(uae_u32 opcode) { printf("Unimplemented: op_2050_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_2058_0_nf(uae_u32 opcode) { printf("Unimplemented: op_2058_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_2060_0_nf(uae_u32 opcode) { printf("Unimplemented: op_2060_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_2068_0_nf(uae_u32 opcode) { printf("Unimplemented: op_2068_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_2070_0_nf(uae_u32 opcode) { printf("Unimplemented: op_2070_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_2070_3_nf(uae_u32 opcode) { printf("Unimplemented: op_2070_3_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_2078_0_nf(uae_u32 opcode) { printf("Unimplemented: op_2078_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_2079_0_nf(uae_u32 opcode) { printf("Unimplemented: op_2079_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_207a_0_nf(uae_u32 opcode) { printf("Unimplemented: op_207a_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_207b_0_nf(uae_u32 opcode) { printf("Unimplemented: op_207b_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_207b_3_nf(uae_u32 opcode) { printf("Unimplemented: op_207b_3_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_207c_0_nf(uae_u32 opcode) { printf("Unimplemented: op_207c_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_3040_0_nf(uae_u32 opcode) { printf("Unimplemented: op_3040_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_3048_0_nf(uae_u32 opcode) { printf("Unimplemented: op_3048_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_3050_0_nf(uae_u32 opcode) { printf("Unimplemented: op_3050_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_3058_0_nf(uae_u32 opcode) { printf("Unimplemented: op_3058_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_3060_0_nf(uae_u32 opcode) { printf("Unimplemented: op_3060_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_3068_0_nf(uae_u32 opcode) { printf("Unimplemented: op_3068_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_3070_0_nf(uae_u32 opcode) { printf("Unimplemented: op_3070_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_3070_3_nf(uae_u32 opcode) { printf("Unimplemented: op_3070_3_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_3078_0_nf(uae_u32 opcode) { printf("Unimplemented: op_3078_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_3079_0_nf(uae_u32 opcode) { printf("Unimplemented: op_3079_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_307a_0_nf(uae_u32 opcode) { printf("Unimplemented: op_307a_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_307b_0_nf(uae_u32 opcode) { printf("Unimplemented: op_307b_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_307b_3_nf(uae_u32 opcode) { printf("Unimplemented: op_307b_3_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_307c_0_nf(uae_u32 opcode) { printf("Unimplemented: op_307c_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_40c0_0_nf(uae_u32 opcode) { printf("Unimplemented: op_40c0_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_40c0_4_nf(uae_u32 opcode) { printf("Unimplemented: op_40c0_4_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_40d0_0_nf(uae_u32 opcode) { printf("Unimplemented: op_40d0_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_40d0_4_nf(uae_u32 opcode) { printf("Unimplemented: op_40d0_4_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_40d8_0_nf(uae_u32 opcode) { printf("Unimplemented: op_40d8_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_40d8_4_nf(uae_u32 opcode) { printf("Unimplemented: op_40d8_4_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_40e0_0_nf(uae_u32 opcode) { printf("Unimplemented: op_40e0_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_40e0_4_nf(uae_u32 opcode) { printf("Unimplemented: op_40e0_4_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_40e8_0_nf(uae_u32 opcode) { printf("Unimplemented: op_40e8_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_40e8_4_nf(uae_u32 opcode) { printf("Unimplemented: op_40e8_4_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_40f0_0_nf(uae_u32 opcode) { printf("Unimplemented: op_40f0_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_40f0_3_nf(uae_u32 opcode) { printf("Unimplemented: op_40f0_3_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_40f0_4_nf(uae_u32 opcode) { printf("Unimplemented: op_40f0_4_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_40f8_0_nf(uae_u32 opcode) { printf("Unimplemented: op_40f8_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_40f8_4_nf(uae_u32 opcode) { printf("Unimplemented: op_40f8_4_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_40f9_0_nf(uae_u32 opcode) { printf("Unimplemented: op_40f9_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_40f9_4_nf(uae_u32 opcode) { printf("Unimplemented: op_40f9_4_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_41d0_0_nf(uae_u32 opcode) { printf("Unimplemented: op_41d0_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_41e8_0_nf(uae_u32 opcode) { printf("Unimplemented: op_41e8_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_41f0_0_nf(uae_u32 opcode) { printf("Unimplemented: op_41f0_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_41f0_3_nf(uae_u32 opcode) { printf("Unimplemented: op_41f0_3_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_41f8_0_nf(uae_u32 opcode) { printf("Unimplemented: op_41f8_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_41f9_0_nf(uae_u32 opcode) { printf("Unimplemented: op_41f9_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_41fa_0_nf(uae_u32 opcode) { printf("Unimplemented: op_41fa_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_41fb_0_nf(uae_u32 opcode) { printf("Unimplemented: op_41fb_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_41fb_3_nf(uae_u32 opcode) { printf("Unimplemented: op_41fb_3_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_42c0_0_nf(uae_u32 opcode) { printf("Unimplemented: op_42c0_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_42d0_0_nf(uae_u32 opcode) { printf("Unimplemented: op_42d0_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_42d8_0_nf(uae_u32 opcode) { printf("Unimplemented: op_42d8_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_42e0_0_nf(uae_u32 opcode) { printf("Unimplemented: op_42e0_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_42e8_0_nf(uae_u32 opcode) { printf("Unimplemented: op_42e8_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_42f0_0_nf(uae_u32 opcode) { printf("Unimplemented: op_42f0_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_42f0_3_nf(uae_u32 opcode) { printf("Unimplemented: op_42f0_3_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_42f8_0_nf(uae_u32 opcode) { printf("Unimplemented: op_42f8_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_42f9_0_nf(uae_u32 opcode) { printf("Unimplemented: op_42f9_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_4808_0_nf(uae_u32 opcode) { printf("Unimplemented: op_4808_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_4848_0_nf(uae_u32 opcode) { printf("Unimplemented: op_4848_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_4850_0_nf(uae_u32 opcode) { printf("Unimplemented: op_4850_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_4868_0_nf(uae_u32 opcode) { printf("Unimplemented: op_4868_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_4870_0_nf(uae_u32 opcode) { printf("Unimplemented: op_4870_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_4870_3_nf(uae_u32 opcode) { printf("Unimplemented: op_4870_3_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_4878_0_nf(uae_u32 opcode) { printf("Unimplemented: op_4878_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_4879_0_nf(uae_u32 opcode) { printf("Unimplemented: op_4879_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_487a_0_nf(uae_u32 opcode) { printf("Unimplemented: op_487a_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_487b_0_nf(uae_u32 opcode) { printf("Unimplemented: op_487b_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_487b_3_nf(uae_u32 opcode) { printf("Unimplemented: op_487b_3_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_4890_0_nf(uae_u32 opcode) { printf("Unimplemented: op_4890_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_48a0_0_nf(uae_u32 opcode) { printf("Unimplemented: op_48a0_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_48a8_0_nf(uae_u32 opcode) { printf("Unimplemented: op_48a8_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_48b0_0_nf(uae_u32 opcode) { printf("Unimplemented: op_48b0_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_48b0_3_nf(uae_u32 opcode) { printf("Unimplemented: op_48b0_3_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_48b8_0_nf(uae_u32 opcode) { printf("Unimplemented: op_48b8_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_48b9_0_nf(uae_u32 opcode) { printf("Unimplemented: op_48b9_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_48d0_0_nf(uae_u32 opcode) { printf("Unimplemented: op_48d0_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_48e0_0_nf(uae_u32 opcode) { printf("Unimplemented: op_48e0_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_48e8_0_nf(uae_u32 opcode) { printf("Unimplemented: op_48e8_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_48f0_0_nf(uae_u32 opcode) { printf("Unimplemented: op_48f0_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_48f0_3_nf(uae_u32 opcode) { printf("Unimplemented: op_48f0_3_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_48f8_0_nf(uae_u32 opcode) { printf("Unimplemented: op_48f8_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_48f9_0_nf(uae_u32 opcode) { printf("Unimplemented: op_48f9_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_4c90_0_nf(uae_u32 opcode) { printf("Unimplemented: op_4c90_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_4c98_0_nf(uae_u32 opcode) { printf("Unimplemented: op_4c98_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_4ca8_0_nf(uae_u32 opcode) { printf("Unimplemented: op_4ca8_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_4cb0_0_nf(uae_u32 opcode) { printf("Unimplemented: op_4cb0_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_4cb0_3_nf(uae_u32 opcode) { printf("Unimplemented: op_4cb0_3_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_4cb8_0_nf(uae_u32 opcode) { printf("Unimplemented: op_4cb8_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_4cb9_0_nf(uae_u32 opcode) { printf("Unimplemented: op_4cb9_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_4cba_0_nf(uae_u32 opcode) { printf("Unimplemented: op_4cba_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_4cbb_0_nf(uae_u32 opcode) { printf("Unimplemented: op_4cbb_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_4cbb_3_nf(uae_u32 opcode) { printf("Unimplemented: op_4cbb_3_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_4cd0_0_nf(uae_u32 opcode) { printf("Unimplemented: op_4cd0_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_4cd8_0_nf(uae_u32 opcode) { printf("Unimplemented: op_4cd8_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_4ce8_0_nf(uae_u32 opcode) { printf("Unimplemented: op_4ce8_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_4cf0_0_nf(uae_u32 opcode) { printf("Unimplemented: op_4cf0_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_4cf0_3_nf(uae_u32 opcode) { printf("Unimplemented: op_4cf0_3_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_4cf8_0_nf(uae_u32 opcode) { printf("Unimplemented: op_4cf8_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_4cf9_0_nf(uae_u32 opcode) { printf("Unimplemented: op_4cf9_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_4cfa_0_nf(uae_u32 opcode) { printf("Unimplemented: op_4cfa_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_4cfb_0_nf(uae_u32 opcode) { printf("Unimplemented: op_4cfb_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_4cfb_3_nf(uae_u32 opcode) { printf("Unimplemented: op_4cfb_3_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_4e40_0_nf(uae_u32 opcode) { printf("Unimplemented: op_4e40_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_4e50_0_nf(uae_u32 opcode) { printf("Unimplemented: op_4e50_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_4e58_0_nf(uae_u32 opcode) { printf("Unimplemented: op_4e58_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_4e60_0_nf(uae_u32 opcode) { printf("Unimplemented: op_4e60_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_4e68_0_nf(uae_u32 opcode) { printf("Unimplemented: op_4e68_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_4e70_0_nf(uae_u32 opcode) { printf("Unimplemented: op_4e70_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_4e71_0_nf(uae_u32 opcode) { printf("Unimplemented: op_4e71_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_4e74_0_nf(uae_u32 opcode) { printf("Unimplemented: op_4e74_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_4e75_0_nf(uae_u32 opcode) { printf("Unimplemented: op_4e75_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_4e76_0_nf(uae_u32 opcode) { printf("Unimplemented: op_4e76_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_4e7a_0_nf(uae_u32 opcode) { printf("Unimplemented: op_4e7a_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_4e7b_0_nf(uae_u32 opcode) { printf("Unimplemented: op_4e7b_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_4e90_0_nf(uae_u32 opcode) { printf("Unimplemented: op_4e90_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_4ea8_0_nf(uae_u32 opcode) { printf("Unimplemented: op_4ea8_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_4eb0_0_nf(uae_u32 opcode) { printf("Unimplemented: op_4eb0_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_4eb0_3_nf(uae_u32 opcode) { printf("Unimplemented: op_4eb0_3_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_4eb8_0_nf(uae_u32 opcode) { printf("Unimplemented: op_4eb8_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_4eb9_0_nf(uae_u32 opcode) { printf("Unimplemented: op_4eb9_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_4eba_0_nf(uae_u32 opcode) { printf("Unimplemented: op_4eba_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_4ebb_0_nf(uae_u32 opcode) { printf("Unimplemented: op_4ebb_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_4ebb_3_nf(uae_u32 opcode) { printf("Unimplemented: op_4ebb_3_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_4ed0_0_nf(uae_u32 opcode) { printf("Unimplemented: op_4ed0_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_4ee8_0_nf(uae_u32 opcode) { printf("Unimplemented: op_4ee8_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_4ef0_0_nf(uae_u32 opcode) { printf("Unimplemented: op_4ef0_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_4ef0_3_nf(uae_u32 opcode) { printf("Unimplemented: op_4ef0_3_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_4ef8_0_nf(uae_u32 opcode) { printf("Unimplemented: op_4ef8_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_4ef9_0_nf(uae_u32 opcode) { printf("Unimplemented: op_4ef9_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_4efa_0_nf(uae_u32 opcode) { printf("Unimplemented: op_4efa_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_4efb_0_nf(uae_u32 opcode) { printf("Unimplemented: op_4efb_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_4efb_3_nf(uae_u32 opcode) { printf("Unimplemented: op_4efb_3_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_5048_0_nf(uae_u32 opcode) { printf("Unimplemented: op_5048_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_5088_0_nf(uae_u32 opcode) { printf("Unimplemented: op_5088_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_50c0_0_nf(uae_u32 opcode) { printf("Unimplemented: op_50c0_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_50c8_0_nf(uae_u32 opcode) { printf("Unimplemented: op_50c8_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_50d0_0_nf(uae_u32 opcode) { printf("Unimplemented: op_50d0_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_50d8_0_nf(uae_u32 opcode) { printf("Unimplemented: op_50d8_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_50e0_0_nf(uae_u32 opcode) { printf("Unimplemented: op_50e0_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_50e8_0_nf(uae_u32 opcode) { printf("Unimplemented: op_50e8_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_50f0_0_nf(uae_u32 opcode) { printf("Unimplemented: op_50f0_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_50f0_3_nf(uae_u32 opcode) { printf("Unimplemented: op_50f0_3_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_50f8_0_nf(uae_u32 opcode) { printf("Unimplemented: op_50f8_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_50f9_0_nf(uae_u32 opcode) { printf("Unimplemented: op_50f9_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_50fa_0_nf(uae_u32 opcode) { printf("Unimplemented: op_50fa_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_50fb_0_nf(uae_u32 opcode) { printf("Unimplemented: op_50fb_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_50fc_0_nf(uae_u32 opcode) { printf("Unimplemented: op_50fc_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_5148_0_nf(uae_u32 opcode) { printf("Unimplemented: op_5148_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_5188_0_nf(uae_u32 opcode) { printf("Unimplemented: op_5188_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_51c0_0_nf(uae_u32 opcode) { printf("Unimplemented: op_51c0_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_51c8_0_nf(uae_u32 opcode) { printf("Unimplemented: op_51c8_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_51d0_0_nf(uae_u32 opcode) { printf("Unimplemented: op_51d0_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_51d8_0_nf(uae_u32 opcode) { printf("Unimplemented: op_51d8_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_51e0_0_nf(uae_u32 opcode) { printf("Unimplemented: op_51e0_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_51e8_0_nf(uae_u32 opcode) { printf("Unimplemented: op_51e8_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_51f0_0_nf(uae_u32 opcode) { printf("Unimplemented: op_51f0_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_51f0_3_nf(uae_u32 opcode) { printf("Unimplemented: op_51f0_3_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_51f8_0_nf(uae_u32 opcode) { printf("Unimplemented: op_51f8_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_51f9_0_nf(uae_u32 opcode) { printf("Unimplemented: op_51f9_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_51fa_0_nf(uae_u32 opcode) { printf("Unimplemented: op_51fa_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_51fb_0_nf(uae_u32 opcode) { printf("Unimplemented: op_51fb_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_51fc_0_nf(uae_u32 opcode) { printf("Unimplemented: op_51fc_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_52c0_0_nf(uae_u32 opcode) { printf("Unimplemented: op_52c0_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_52c8_0_nf(uae_u32 opcode) { printf("Unimplemented: op_52c8_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_52d0_0_nf(uae_u32 opcode) { printf("Unimplemented: op_52d0_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_52d8_0_nf(uae_u32 opcode) { printf("Unimplemented: op_52d8_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_52e0_0_nf(uae_u32 opcode) { printf("Unimplemented: op_52e0_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_52e8_0_nf(uae_u32 opcode) { printf("Unimplemented: op_52e8_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_52f0_0_nf(uae_u32 opcode) { printf("Unimplemented: op_52f0_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_52f0_3_nf(uae_u32 opcode) { printf("Unimplemented: op_52f0_3_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_52f8_0_nf(uae_u32 opcode) { printf("Unimplemented: op_52f8_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_52f9_0_nf(uae_u32 opcode) { printf("Unimplemented: op_52f9_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_52fa_0_nf(uae_u32 opcode) { printf("Unimplemented: op_52fa_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_52fb_0_nf(uae_u32 opcode) { printf("Unimplemented: op_52fb_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_52fc_0_nf(uae_u32 opcode) { printf("Unimplemented: op_52fc_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_53c0_0_nf(uae_u32 opcode) { printf("Unimplemented: op_53c0_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_53c8_0_nf(uae_u32 opcode) { printf("Unimplemented: op_53c8_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_53d0_0_nf(uae_u32 opcode) { printf("Unimplemented: op_53d0_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_53d8_0_nf(uae_u32 opcode) { printf("Unimplemented: op_53d8_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_53e0_0_nf(uae_u32 opcode) { printf("Unimplemented: op_53e0_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_53e8_0_nf(uae_u32 opcode) { printf("Unimplemented: op_53e8_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_53f0_0_nf(uae_u32 opcode) { printf("Unimplemented: op_53f0_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_53f0_3_nf(uae_u32 opcode) { printf("Unimplemented: op_53f0_3_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_53f8_0_nf(uae_u32 opcode) { printf("Unimplemented: op_53f8_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_53f9_0_nf(uae_u32 opcode) { printf("Unimplemented: op_53f9_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_53fa_0_nf(uae_u32 opcode) { printf("Unimplemented: op_53fa_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_53fb_0_nf(uae_u32 opcode) { printf("Unimplemented: op_53fb_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_53fc_0_nf(uae_u32 opcode) { printf("Unimplemented: op_53fc_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_54c0_0_nf(uae_u32 opcode) { printf("Unimplemented: op_54c0_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_54c8_0_nf(uae_u32 opcode) { printf("Unimplemented: op_54c8_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_54d0_0_nf(uae_u32 opcode) { printf("Unimplemented: op_54d0_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_54d8_0_nf(uae_u32 opcode) { printf("Unimplemented: op_54d8_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_54e0_0_nf(uae_u32 opcode) { printf("Unimplemented: op_54e0_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_54e8_0_nf(uae_u32 opcode) { printf("Unimplemented: op_54e8_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_54f0_0_nf(uae_u32 opcode) { printf("Unimplemented: op_54f0_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_54f0_3_nf(uae_u32 opcode) { printf("Unimplemented: op_54f0_3_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_54f8_0_nf(uae_u32 opcode) { printf("Unimplemented: op_54f8_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_54f9_0_nf(uae_u32 opcode) { printf("Unimplemented: op_54f9_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_54fa_0_nf(uae_u32 opcode) { printf("Unimplemented: op_54fa_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_54fb_0_nf(uae_u32 opcode) { printf("Unimplemented: op_54fb_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_54fc_0_nf(uae_u32 opcode) { printf("Unimplemented: op_54fc_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_55c0_0_nf(uae_u32 opcode) { printf("Unimplemented: op_55c0_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_55c8_0_nf(uae_u32 opcode) { printf("Unimplemented: op_55c8_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_55d0_0_nf(uae_u32 opcode) { printf("Unimplemented: op_55d0_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_55d8_0_nf(uae_u32 opcode) { printf("Unimplemented: op_55d8_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_55e0_0_nf(uae_u32 opcode) { printf("Unimplemented: op_55e0_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_55e8_0_nf(uae_u32 opcode) { printf("Unimplemented: op_55e8_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_55f0_0_nf(uae_u32 opcode) { printf("Unimplemented: op_55f0_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_55f0_3_nf(uae_u32 opcode) { printf("Unimplemented: op_55f0_3_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_55f8_0_nf(uae_u32 opcode) { printf("Unimplemented: op_55f8_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_55f9_0_nf(uae_u32 opcode) { printf("Unimplemented: op_55f9_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_55fa_0_nf(uae_u32 opcode) { printf("Unimplemented: op_55fa_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_55fb_0_nf(uae_u32 opcode) { printf("Unimplemented: op_55fb_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_55fc_0_nf(uae_u32 opcode) { printf("Unimplemented: op_55fc_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_56c0_0_nf(uae_u32 opcode) { printf("Unimplemented: op_56c0_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_56c8_0_nf(uae_u32 opcode) { printf("Unimplemented: op_56c8_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_56d0_0_nf(uae_u32 opcode) { printf("Unimplemented: op_56d0_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_56d8_0_nf(uae_u32 opcode) { printf("Unimplemented: op_56d8_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_56e0_0_nf(uae_u32 opcode) { printf("Unimplemented: op_56e0_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_56e8_0_nf(uae_u32 opcode) { printf("Unimplemented: op_56e8_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_56f0_0_nf(uae_u32 opcode) { printf("Unimplemented: op_56f0_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_56f0_3_nf(uae_u32 opcode) { printf("Unimplemented: op_56f0_3_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_56f8_0_nf(uae_u32 opcode) { printf("Unimplemented: op_56f8_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_56f9_0_nf(uae_u32 opcode) { printf("Unimplemented: op_56f9_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_56fa_0_nf(uae_u32 opcode) { printf("Unimplemented: op_56fa_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_56fb_0_nf(uae_u32 opcode) { printf("Unimplemented: op_56fb_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_56fc_0_nf(uae_u32 opcode) { printf("Unimplemented: op_56fc_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_57c0_0_nf(uae_u32 opcode) { printf("Unimplemented: op_57c0_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_57c8_0_nf(uae_u32 opcode) { printf("Unimplemented: op_57c8_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_57d0_0_nf(uae_u32 opcode) { printf("Unimplemented: op_57d0_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_57d8_0_nf(uae_u32 opcode) { printf("Unimplemented: op_57d8_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_57e0_0_nf(uae_u32 opcode) { printf("Unimplemented: op_57e0_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_57e8_0_nf(uae_u32 opcode) { printf("Unimplemented: op_57e8_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_57f0_0_nf(uae_u32 opcode) { printf("Unimplemented: op_57f0_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_57f0_3_nf(uae_u32 opcode) { printf("Unimplemented: op_57f0_3_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_57f8_0_nf(uae_u32 opcode) { printf("Unimplemented: op_57f8_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_57f9_0_nf(uae_u32 opcode) { printf("Unimplemented: op_57f9_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_57fa_0_nf(uae_u32 opcode) { printf("Unimplemented: op_57fa_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_57fb_0_nf(uae_u32 opcode) { printf("Unimplemented: op_57fb_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_57fc_0_nf(uae_u32 opcode) { printf("Unimplemented: op_57fc_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_58c0_0_nf(uae_u32 opcode) { printf("Unimplemented: op_58c0_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_58c8_0_nf(uae_u32 opcode) { printf("Unimplemented: op_58c8_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_58d0_0_nf(uae_u32 opcode) { printf("Unimplemented: op_58d0_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_58d8_0_nf(uae_u32 opcode) { printf("Unimplemented: op_58d8_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_58e0_0_nf(uae_u32 opcode) { printf("Unimplemented: op_58e0_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_58e8_0_nf(uae_u32 opcode) { printf("Unimplemented: op_58e8_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_58f0_0_nf(uae_u32 opcode) { printf("Unimplemented: op_58f0_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_58f0_3_nf(uae_u32 opcode) { printf("Unimplemented: op_58f0_3_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_58f8_0_nf(uae_u32 opcode) { printf("Unimplemented: op_58f8_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_58f9_0_nf(uae_u32 opcode) { printf("Unimplemented: op_58f9_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_58fa_0_nf(uae_u32 opcode) { printf("Unimplemented: op_58fa_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_58fb_0_nf(uae_u32 opcode) { printf("Unimplemented: op_58fb_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_58fc_0_nf(uae_u32 opcode) { printf("Unimplemented: op_58fc_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_59c0_0_nf(uae_u32 opcode) { printf("Unimplemented: op_59c0_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_59c8_0_nf(uae_u32 opcode) { printf("Unimplemented: op_59c8_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_59d0_0_nf(uae_u32 opcode) { printf("Unimplemented: op_59d0_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_59d8_0_nf(uae_u32 opcode) { printf("Unimplemented: op_59d8_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_59e0_0_nf(uae_u32 opcode) { printf("Unimplemented: op_59e0_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_59e8_0_nf(uae_u32 opcode) { printf("Unimplemented: op_59e8_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_59f0_0_nf(uae_u32 opcode) { printf("Unimplemented: op_59f0_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_59f0_3_nf(uae_u32 opcode) { printf("Unimplemented: op_59f0_3_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_59f8_0_nf(uae_u32 opcode) { printf("Unimplemented: op_59f8_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_59f9_0_nf(uae_u32 opcode) { printf("Unimplemented: op_59f9_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_59fa_0_nf(uae_u32 opcode) { printf("Unimplemented: op_59fa_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_59fb_0_nf(uae_u32 opcode) { printf("Unimplemented: op_59fb_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_59fc_0_nf(uae_u32 opcode) { printf("Unimplemented: op_59fc_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_5ac0_0_nf(uae_u32 opcode) { printf("Unimplemented: op_5ac0_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_5ac8_0_nf(uae_u32 opcode) { printf("Unimplemented: op_5ac8_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_5ad0_0_nf(uae_u32 opcode) { printf("Unimplemented: op_5ad0_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_5ad8_0_nf(uae_u32 opcode) { printf("Unimplemented: op_5ad8_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_5ae0_0_nf(uae_u32 opcode) { printf("Unimplemented: op_5ae0_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_5ae8_0_nf(uae_u32 opcode) { printf("Unimplemented: op_5ae8_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_5af0_0_nf(uae_u32 opcode) { printf("Unimplemented: op_5af0_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_5af0_3_nf(uae_u32 opcode) { printf("Unimplemented: op_5af0_3_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_5af8_0_nf(uae_u32 opcode) { printf("Unimplemented: op_5af8_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_5af9_0_nf(uae_u32 opcode) { printf("Unimplemented: op_5af9_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_5afa_0_nf(uae_u32 opcode) { printf("Unimplemented: op_5afa_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_5afb_0_nf(uae_u32 opcode) { printf("Unimplemented: op_5afb_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_5afc_0_nf(uae_u32 opcode) { printf("Unimplemented: op_5afc_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_5bc0_0_nf(uae_u32 opcode) { printf("Unimplemented: op_5bc0_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_5bc8_0_nf(uae_u32 opcode) { printf("Unimplemented: op_5bc8_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_5bd0_0_nf(uae_u32 opcode) { printf("Unimplemented: op_5bd0_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_5bd8_0_nf(uae_u32 opcode) { printf("Unimplemented: op_5bd8_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_5be0_0_nf(uae_u32 opcode) { printf("Unimplemented: op_5be0_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_5be8_0_nf(uae_u32 opcode) { printf("Unimplemented: op_5be8_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_5bf0_0_nf(uae_u32 opcode) { printf("Unimplemented: op_5bf0_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_5bf0_3_nf(uae_u32 opcode) { printf("Unimplemented: op_5bf0_3_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_5bf8_0_nf(uae_u32 opcode) { printf("Unimplemented: op_5bf8_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_5bf9_0_nf(uae_u32 opcode) { printf("Unimplemented: op_5bf9_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_5bfa_0_nf(uae_u32 opcode) { printf("Unimplemented: op_5bfa_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_5bfb_0_nf(uae_u32 opcode) { printf("Unimplemented: op_5bfb_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_5bfc_0_nf(uae_u32 opcode) { printf("Unimplemented: op_5bfc_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_5cc0_0_nf(uae_u32 opcode) { printf("Unimplemented: op_5cc0_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_5cc8_0_nf(uae_u32 opcode) { printf("Unimplemented: op_5cc8_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_5cd0_0_nf(uae_u32 opcode) { printf("Unimplemented: op_5cd0_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_5cd8_0_nf(uae_u32 opcode) { printf("Unimplemented: op_5cd8_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_5ce0_0_nf(uae_u32 opcode) { printf("Unimplemented: op_5ce0_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_5ce8_0_nf(uae_u32 opcode) { printf("Unimplemented: op_5ce8_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_5cf0_0_nf(uae_u32 opcode) { printf("Unimplemented: op_5cf0_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_5cf0_3_nf(uae_u32 opcode) { printf("Unimplemented: op_5cf0_3_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_5cf8_0_nf(uae_u32 opcode) { printf("Unimplemented: op_5cf8_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_5cf9_0_nf(uae_u32 opcode) { printf("Unimplemented: op_5cf9_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_5cfa_0_nf(uae_u32 opcode) { printf("Unimplemented: op_5cfa_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_5cfb_0_nf(uae_u32 opcode) { printf("Unimplemented: op_5cfb_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_5cfc_0_nf(uae_u32 opcode) { printf("Unimplemented: op_5cfc_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_5dc0_0_nf(uae_u32 opcode) { printf("Unimplemented: op_5dc0_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_5dc8_0_nf(uae_u32 opcode) { printf("Unimplemented: op_5dc8_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_5dd0_0_nf(uae_u32 opcode) { printf("Unimplemented: op_5dd0_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_5dd8_0_nf(uae_u32 opcode) { printf("Unimplemented: op_5dd8_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_5de0_0_nf(uae_u32 opcode) { printf("Unimplemented: op_5de0_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_5de8_0_nf(uae_u32 opcode) { printf("Unimplemented: op_5de8_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_5df0_0_nf(uae_u32 opcode) { printf("Unimplemented: op_5df0_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_5df0_3_nf(uae_u32 opcode) { printf("Unimplemented: op_5df0_3_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_5df8_0_nf(uae_u32 opcode) { printf("Unimplemented: op_5df8_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_5df9_0_nf(uae_u32 opcode) { printf("Unimplemented: op_5df9_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_5dfa_0_nf(uae_u32 opcode) { printf("Unimplemented: op_5dfa_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_5dfb_0_nf(uae_u32 opcode) { printf("Unimplemented: op_5dfb_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_5dfc_0_nf(uae_u32 opcode) { printf("Unimplemented: op_5dfc_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_5ec0_0_nf(uae_u32 opcode) { printf("Unimplemented: op_5ec0_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_5ec8_0_nf(uae_u32 opcode) { printf("Unimplemented: op_5ec8_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_5ed0_0_nf(uae_u32 opcode) { printf("Unimplemented: op_5ed0_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_5ed8_0_nf(uae_u32 opcode) { printf("Unimplemented: op_5ed8_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_5ee0_0_nf(uae_u32 opcode) { printf("Unimplemented: op_5ee0_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_5ee8_0_nf(uae_u32 opcode) { printf("Unimplemented: op_5ee8_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_5ef0_0_nf(uae_u32 opcode) { printf("Unimplemented: op_5ef0_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_5ef0_3_nf(uae_u32 opcode) { printf("Unimplemented: op_5ef0_3_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_5ef8_0_nf(uae_u32 opcode) { printf("Unimplemented: op_5ef8_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_5ef9_0_nf(uae_u32 opcode) { printf("Unimplemented: op_5ef9_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_5efa_0_nf(uae_u32 opcode) { printf("Unimplemented: op_5efa_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_5efb_0_nf(uae_u32 opcode) { printf("Unimplemented: op_5efb_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_5efc_0_nf(uae_u32 opcode) { printf("Unimplemented: op_5efc_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_5fc0_0_nf(uae_u32 opcode) { printf("Unimplemented: op_5fc0_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_5fc8_0_nf(uae_u32 opcode) { printf("Unimplemented: op_5fc8_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_5fd0_0_nf(uae_u32 opcode) { printf("Unimplemented: op_5fd0_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_5fd8_0_nf(uae_u32 opcode) { printf("Unimplemented: op_5fd8_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_5fe0_0_nf(uae_u32 opcode) { printf("Unimplemented: op_5fe0_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_5fe8_0_nf(uae_u32 opcode) { printf("Unimplemented: op_5fe8_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_5ff0_0_nf(uae_u32 opcode) { printf("Unimplemented: op_5ff0_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_5ff0_3_nf(uae_u32 opcode) { printf("Unimplemented: op_5ff0_3_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_5ff8_0_nf(uae_u32 opcode) { printf("Unimplemented: op_5ff8_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_5ff9_0_nf(uae_u32 opcode) { printf("Unimplemented: op_5ff9_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_5ffa_0_nf(uae_u32 opcode) { printf("Unimplemented: op_5ffa_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_5ffb_0_nf(uae_u32 opcode) { printf("Unimplemented: op_5ffb_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_5ffc_0_nf(uae_u32 opcode) { printf("Unimplemented: op_5ffc_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_6000_0_nf(uae_u32 opcode) { printf("Unimplemented: op_6000_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_6001_0_nf(uae_u32 opcode) { printf("Unimplemented: op_6001_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_60ff_0_nf(uae_u32 opcode) { printf("Unimplemented: op_60ff_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_60ff_3_nf(uae_u32 opcode) { printf("Unimplemented: op_60ff_3_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_6100_0_nf(uae_u32 opcode) { printf("Unimplemented: op_6100_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_6101_0_nf(uae_u32 opcode) { printf("Unimplemented: op_6101_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_61ff_0_nf(uae_u32 opcode) { printf("Unimplemented: op_61ff_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_6200_0_nf(uae_u32 opcode) { printf("Unimplemented: op_6200_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_6201_0_nf(uae_u32 opcode) { printf("Unimplemented: op_6201_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_62ff_0_nf(uae_u32 opcode) { printf("Unimplemented: op_62ff_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_62ff_3_nf(uae_u32 opcode) { printf("Unimplemented: op_62ff_3_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_6300_0_nf(uae_u32 opcode) { printf("Unimplemented: op_6300_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_6301_0_nf(uae_u32 opcode) { printf("Unimplemented: op_6301_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_63ff_0_nf(uae_u32 opcode) { printf("Unimplemented: op_63ff_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_63ff_3_nf(uae_u32 opcode) { printf("Unimplemented: op_63ff_3_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_6400_0_nf(uae_u32 opcode) { printf("Unimplemented: op_6400_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_6401_0_nf(uae_u32 opcode) { printf("Unimplemented: op_6401_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_64ff_0_nf(uae_u32 opcode) { printf("Unimplemented: op_64ff_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_64ff_3_nf(uae_u32 opcode) { printf("Unimplemented: op_64ff_3_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_6500_0_nf(uae_u32 opcode) { printf("Unimplemented: op_6500_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_6501_0_nf(uae_u32 opcode) { printf("Unimplemented: op_6501_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_65ff_0_nf(uae_u32 opcode) { printf("Unimplemented: op_65ff_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_65ff_3_nf(uae_u32 opcode) { printf("Unimplemented: op_65ff_3_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_6600_0_nf(uae_u32 opcode) { printf("Unimplemented: op_6600_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_6601_0_nf(uae_u32 opcode) { printf("Unimplemented: op_6601_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_66ff_0_nf(uae_u32 opcode) { printf("Unimplemented: op_66ff_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_66ff_3_nf(uae_u32 opcode) { printf("Unimplemented: op_66ff_3_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_6700_0_nf(uae_u32 opcode) { printf("Unimplemented: op_6700_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_6701_0_nf(uae_u32 opcode) { printf("Unimplemented: op_6701_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_67ff_0_nf(uae_u32 opcode) { printf("Unimplemented: op_67ff_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_67ff_3_nf(uae_u32 opcode) { printf("Unimplemented: op_67ff_3_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_6800_0_nf(uae_u32 opcode) { printf("Unimplemented: op_6800_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_6801_0_nf(uae_u32 opcode) { printf("Unimplemented: op_6801_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_68ff_0_nf(uae_u32 opcode) { printf("Unimplemented: op_68ff_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_68ff_3_nf(uae_u32 opcode) { printf("Unimplemented: op_68ff_3_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_6900_0_nf(uae_u32 opcode) { printf("Unimplemented: op_6900_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_6901_0_nf(uae_u32 opcode) { printf("Unimplemented: op_6901_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_69ff_0_nf(uae_u32 opcode) { printf("Unimplemented: op_69ff_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_69ff_3_nf(uae_u32 opcode) { printf("Unimplemented: op_69ff_3_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_6a00_0_nf(uae_u32 opcode) { printf("Unimplemented: op_6a00_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_6a01_0_nf(uae_u32 opcode) { printf("Unimplemented: op_6a01_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_6aff_0_nf(uae_u32 opcode) { printf("Unimplemented: op_6aff_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_6aff_3_nf(uae_u32 opcode) { printf("Unimplemented: op_6aff_3_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_6b00_0_nf(uae_u32 opcode) { printf("Unimplemented: op_6b00_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_6b01_0_nf(uae_u32 opcode) { printf("Unimplemented: op_6b01_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_6bff_0_nf(uae_u32 opcode) { printf("Unimplemented: op_6bff_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_6bff_3_nf(uae_u32 opcode) { printf("Unimplemented: op_6bff_3_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_6c00_0_nf(uae_u32 opcode) { printf("Unimplemented: op_6c00_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_6c01_0_nf(uae_u32 opcode) { printf("Unimplemented: op_6c01_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_6cff_0_nf(uae_u32 opcode) { printf("Unimplemented: op_6cff_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_6cff_3_nf(uae_u32 opcode) { printf("Unimplemented: op_6cff_3_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_6d00_0_nf(uae_u32 opcode) { printf("Unimplemented: op_6d00_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_6d0_0_nf(uae_u32 opcode) { printf("Unimplemented: op_6d0_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_6d01_0_nf(uae_u32 opcode) { printf("Unimplemented: op_6d01_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_6dff_0_nf(uae_u32 opcode) { printf("Unimplemented: op_6dff_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_6dff_3_nf(uae_u32 opcode) { printf("Unimplemented: op_6dff_3_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_6e00_0_nf(uae_u32 opcode) { printf("Unimplemented: op_6e00_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_6e01_0_nf(uae_u32 opcode) { printf("Unimplemented: op_6e01_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_6e8_0_nf(uae_u32 opcode) { printf("Unimplemented: op_6e8_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_6eff_0_nf(uae_u32 opcode) { printf("Unimplemented: op_6eff_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_6eff_3_nf(uae_u32 opcode) { printf("Unimplemented: op_6eff_3_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_6f00_0_nf(uae_u32 opcode) { printf("Unimplemented: op_6f00_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_6f0_0_nf(uae_u32 opcode) { printf("Unimplemented: op_6f0_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_6f01_0_nf(uae_u32 opcode) { printf("Unimplemented: op_6f01_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_6f8_0_nf(uae_u32 opcode) { printf("Unimplemented: op_6f8_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_6f9_0_nf(uae_u32 opcode) { printf("Unimplemented: op_6f9_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_6fa_0_nf(uae_u32 opcode) { printf("Unimplemented: op_6fa_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_6fb_0_nf(uae_u32 opcode) { printf("Unimplemented: op_6fb_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_6fff_0_nf(uae_u32 opcode) { printf("Unimplemented: op_6fff_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_6fff_3_nf(uae_u32 opcode) { printf("Unimplemented: op_6fff_3_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_7100_0_nf(uae_u32 opcode) { printf("Unimplemented: op_7100_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_7101_0_nf(uae_u32 opcode) { printf("Unimplemented: op_7101_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_8140_0_nf(uae_u32 opcode) { printf("Unimplemented: op_8140_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_8148_0_nf(uae_u32 opcode) { printf("Unimplemented: op_8148_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_8180_0_nf(uae_u32 opcode) { printf("Unimplemented: op_8180_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_8188_0_nf(uae_u32 opcode) { printf("Unimplemented: op_8188_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_90c0_0_nf(uae_u32 opcode) { printf("Unimplemented: op_90c0_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_90c8_0_nf(uae_u32 opcode) { printf("Unimplemented: op_90c8_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_90d0_0_nf(uae_u32 opcode) { printf("Unimplemented: op_90d0_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_90d8_0_nf(uae_u32 opcode) { printf("Unimplemented: op_90d8_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_90e0_0_nf(uae_u32 opcode) { printf("Unimplemented: op_90e0_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_90e8_0_nf(uae_u32 opcode) { printf("Unimplemented: op_90e8_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_90f0_0_nf(uae_u32 opcode) { printf("Unimplemented: op_90f0_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_90f0_3_nf(uae_u32 opcode) { printf("Unimplemented: op_90f0_3_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_90f8_0_nf(uae_u32 opcode) { printf("Unimplemented: op_90f8_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_90f9_0_nf(uae_u32 opcode) { printf("Unimplemented: op_90f9_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_90fa_0_nf(uae_u32 opcode) { printf("Unimplemented: op_90fa_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_90fb_0_nf(uae_u32 opcode) { printf("Unimplemented: op_90fb_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_90fb_3_nf(uae_u32 opcode) { printf("Unimplemented: op_90fb_3_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_90fc_0_nf(uae_u32 opcode) { printf("Unimplemented: op_90fc_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_91c0_0_nf(uae_u32 opcode) { printf("Unimplemented: op_91c0_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_91c8_0_nf(uae_u32 opcode) { printf("Unimplemented: op_91c8_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_91d0_0_nf(uae_u32 opcode) { printf("Unimplemented: op_91d0_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_91d8_0_nf(uae_u32 opcode) { printf("Unimplemented: op_91d8_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_91e0_0_nf(uae_u32 opcode) { printf("Unimplemented: op_91e0_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_91e8_0_nf(uae_u32 opcode) { printf("Unimplemented: op_91e8_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_91f0_0_nf(uae_u32 opcode) { printf("Unimplemented: op_91f0_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_91f0_3_nf(uae_u32 opcode) { printf("Unimplemented: op_91f0_3_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_91f8_0_nf(uae_u32 opcode) { printf("Unimplemented: op_91f8_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_91f9_0_nf(uae_u32 opcode) { printf("Unimplemented: op_91f9_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_91fa_0_nf(uae_u32 opcode) { printf("Unimplemented: op_91fa_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_91fb_0_nf(uae_u32 opcode) { printf("Unimplemented: op_91fb_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_91fb_3_nf(uae_u32 opcode) { printf("Unimplemented: op_91fb_3_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_91fc_0_nf(uae_u32 opcode) { printf("Unimplemented: op_91fc_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_c140_0_nf(uae_u32 opcode) { printf("Unimplemented: op_c140_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_c148_0_nf(uae_u32 opcode) { printf("Unimplemented: op_c148_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_c188_0_nf(uae_u32 opcode) { printf("Unimplemented: op_c188_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_d0c0_0_nf(uae_u32 opcode) { printf("Unimplemented: op_d0c0_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_d0c8_0_nf(uae_u32 opcode) { printf("Unimplemented: op_d0c8_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_d0d0_0_nf(uae_u32 opcode) { printf("Unimplemented: op_d0d0_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_d0d8_0_nf(uae_u32 opcode) { printf("Unimplemented: op_d0d8_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_d0e0_0_nf(uae_u32 opcode) { printf("Unimplemented: op_d0e0_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_d0e8_0_nf(uae_u32 opcode) { printf("Unimplemented: op_d0e8_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_d0f0_0_nf(uae_u32 opcode) { printf("Unimplemented: op_d0f0_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_d0f0_3_nf(uae_u32 opcode) { printf("Unimplemented: op_d0f0_3_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_d0f8_0_nf(uae_u32 opcode) { printf("Unimplemented: op_d0f8_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_d0f9_0_nf(uae_u32 opcode) { printf("Unimplemented: op_d0f9_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_d0fa_0_nf(uae_u32 opcode) { printf("Unimplemented: op_d0fa_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_d0fb_0_nf(uae_u32 opcode) { printf("Unimplemented: op_d0fb_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_d0fb_3_nf(uae_u32 opcode) { printf("Unimplemented: op_d0fb_3_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_d0fc_0_nf(uae_u32 opcode) { printf("Unimplemented: op_d0fc_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_d1c0_0_nf(uae_u32 opcode) { printf("Unimplemented: op_d1c0_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_d1c8_0_nf(uae_u32 opcode) { printf("Unimplemented: op_d1c8_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_d1d0_0_nf(uae_u32 opcode) { printf("Unimplemented: op_d1d0_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_d1d8_0_nf(uae_u32 opcode) { printf("Unimplemented: op_d1d8_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_d1e0_0_nf(uae_u32 opcode) { printf("Unimplemented: op_d1e0_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_d1e8_0_nf(uae_u32 opcode) { printf("Unimplemented: op_d1e8_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_d1f0_0_nf(uae_u32 opcode) { printf("Unimplemented: op_d1f0_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_d1f0_3_nf(uae_u32 opcode) { printf("Unimplemented: op_d1f0_3_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_d1f8_0_nf(uae_u32 opcode) { printf("Unimplemented: op_d1f8_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_d1f9_0_nf(uae_u32 opcode) { printf("Unimplemented: op_d1f9_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_d1fa_0_nf(uae_u32 opcode) { printf("Unimplemented: op_d1fa_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_d1fb_0_nf(uae_u32 opcode) { printf("Unimplemented: op_d1fb_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_d1fb_3_nf(uae_u32 opcode) { printf("Unimplemented: op_d1fb_3_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_d1fc_0_nf(uae_u32 opcode) { printf("Unimplemented: op_d1fc_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_e10_0_nf(uae_u32 opcode) { printf("Unimplemented: op_e10_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_e18_0_nf(uae_u32 opcode) { printf("Unimplemented: op_e18_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_e20_0_nf(uae_u32 opcode) { printf("Unimplemented: op_e20_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_e28_0_nf(uae_u32 opcode) { printf("Unimplemented: op_e28_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_e30_0_nf(uae_u32 opcode) { printf("Unimplemented: op_e30_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_e38_0_nf(uae_u32 opcode) { printf("Unimplemented: op_e38_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_e39_0_nf(uae_u32 opcode) { printf("Unimplemented: op_e39_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_e50_0_nf(uae_u32 opcode) { printf("Unimplemented: op_e50_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_e58_0_nf(uae_u32 opcode) { printf("Unimplemented: op_e58_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_e60_0_nf(uae_u32 opcode) { printf("Unimplemented: op_e60_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_e68_0_nf(uae_u32 opcode) { printf("Unimplemented: op_e68_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_e70_0_nf(uae_u32 opcode) { printf("Unimplemented: op_e70_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_e78_0_nf(uae_u32 opcode) { printf("Unimplemented: op_e78_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_e79_0_nf(uae_u32 opcode) { printf("Unimplemented: op_e79_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_e90_0_nf(uae_u32 opcode) { printf("Unimplemented: op_e90_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_e98_0_nf(uae_u32 opcode) { printf("Unimplemented: op_e98_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_ea0_0_nf(uae_u32 opcode) { printf("Unimplemented: op_ea0_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_ea8_0_nf(uae_u32 opcode) { printf("Unimplemented: op_ea8_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_eb0_0_nf(uae_u32 opcode) { printf("Unimplemented: op_eb0_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_eb8_0_nf(uae_u32 opcode) { printf("Unimplemented: op_eb8_0_nf 0x%04x\\n", opcode); }
void REGPARAM2 op_eb9_0_nf(uae_u32 opcode) { printf("Unimplemented: op_eb9_0_nf 0x%04x\\n", opcode); }

// readcpu.cpp needs these - stubs for now since we use pre-generated tables
// Removed defs68k[] and n_defs68k stubs - now using generated cpudefs.cpp

// FPU operation stubs (needed for _ff functions that reference FPU ops)
void REGPARAM2 fpuop_arithmetic(uae_u32 opcode, uae_u32 extra) {
    fprintf(stderr, "FPU arithmetic not implemented: opcode=0x%04x extra=0x%04x\n", opcode, extra);
    abort();
}

void REGPARAM2 fpuop_scc(uae_u32 opcode, uae_u32 extra) {
    fprintf(stderr, "FPU scc not implemented: opcode=0x%04x extra=0x%04x\n", opcode, extra);
    abort();
}

void REGPARAM2 fpuop_dbcc(uae_u32 opcode, uae_u32 extra) {
    fprintf(stderr, "FPU dbcc not implemented: opcode=0x%04x extra=0x%04x\n", opcode, extra);
    abort();
}

void REGPARAM2 fpuop_trapcc(uae_u32 opcode, uae_u32 extra) {
    fprintf(stderr, "FPU trapcc not implemented: opcode=0x%04x extra=0x%04x\n", opcode, extra);
    abort();
}

void REGPARAM2 fpuop_bcc(uae_u32 opcode, uae_u32 extra, uae_u32 pc) {
    fprintf(stderr, "FPU bcc not implemented: opcode=0x%04x extra=0x%04x pc=0x%08x\n", opcode, extra, pc);
    abort();
}

void REGPARAM2 fpuop_save(uae_u32 opcode) {
    fprintf(stderr, "FPU save not implemented: opcode=0x%04x\n", opcode);
    abort();
}

void REGPARAM2 fpuop_restore(uae_u32 opcode) {
    fprintf(stderr, "FPU restore not implemented: opcode=0x%04x\n", opcode);
    abort();
}
